#!/usr/bin/env zsh

bindkey \^U backward-kill-line
export TERM='xterm-256color'
source $HOME/tools/sac/bin/sacinit.sh
test -e $HOME/tools/sac/bin && export PATH=$HOME/tools/sac/bin:$PATH
export WINEARCH=win32
